#!/bin/sh

path=$(echo $PATH | grep '/home/yinanfang/webapps/likeit/bin')
if [ -z "$path" ]; then
  export PATH=$PATH:/home/yinanfang/webapps/likeit/bin
fi

GIT_WORK_TREE=/home/yinanfang/webapps/likeit/app git checkout -f master
GIT_WORK_TREE=/home/yinanfang/webapps/likeit/app git reset --hard


/home/yinanfang/webapps/likeit/bin/stop
/home/yinanfang/webapps/likeit/bin/start
