#!/bin/sh

# Test script inspired by http://blog.apiary.io/2013/10/17/How-to-test-api-with-api-blueprint-and-dredd/
echo 'Start Travis CI Integration Test'
node app.js &
sleep 3
PID=$!
node_modules/karma/bin/karma start karma.conf.js --single-run
jasmine-node ./test/api
kill -9 $PID
